name: gromacs_py
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - gromacs=2019.1
  - ambertools=20.9
  - jupyter
  - rdkit
  - pip
  - pip:
    - gromacs_py
    - git+https://github.com/alanwilter/acpype.git