name: gromacs_py
channels:
  - conda-forge
  - bioconda
  - acellera
dependencies:
  - python=3.7
  - scipy 
  - matplotlib 
  - gromacs 
  - pandoc
  - htmd-pdb2pqr
  - pip
  - pip:
    - codecov
    - pytest-cov
    - gromacs_py