language: python
sudo: false

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - cd ..
  - git clone https://github.com/Electrostatics/apbs-pdb2pqr.git --branch master --depth=1
  - cd apbs-pdb2pqr/pdb2pqr/
  - python2 scons/scons.py install --prefix=$HOME

branches:
    only:
      - master

script:
  - ./gromacs_py/test_gromacs_py.py