# https://github.com/astropy/ci-helpers/blob/master/.travis.yml

# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: generic

os:
    - linux

sudo: false

env:
  global:
    - SETUP_CMD='test'
    - TEST_CMD='./gromacs_py/test_gromacs_py.py'
    - PYTHON_VERSION=3.6
    - CONDA_DEPENDENCIES="scipy matplotlib gromacs"
    - CONDA_CHANNELS="defaults conda-forge bioconda"
    - NUMPY_VERSION=stable

    matrix:
        - GROMACS_VERSION=2019.1  PYTHON_VERSION=3.6

matrix:
    include:
        # pytest pip fallback, conda package for 3.1 is not available for py3.4
        - os: linux
          env: PYTHON_VERSION=3.4
        - os: ;inux
          env: PYTHON_VERSION=3.7

install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - pip install -r requirements.txt
  - cd ..
  - git clone https://github.com/Electrostatics/apbs-pdb2pqr.git --branch master --depth=1
  - cd apbs-pdb2pqr/pdb2pqr/
  - python2 scons/scons.py install
  - export PATH="/home/travis/pdb2pqr/:$PATH"
  - ls ${TRAVIS_BUILD_DIR}

script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./gromacs_py/test_gromacs_py.py

#after_success:
#- if [[ $SETUP_CMD == *coverage* ]]; then coveralls; fi

#language: python
#
#python:
#  - "3.6"
#
#os:
#  - linux
#
#sudo: false
#
#git:
#  depth: false
#
##before_install: 
##  - python install 2.7 
#
#install:
#  - #git clone https://github.com/samuelmurail/gromacs_py.git
#  - pwd
#  - pip install -r requirements.txt
#  - cd ..
#  - git clone https://github.com/Electrostatics/apbs-pdb2pqr.git --branch master --depth=1
#  - cd apbs-pdb2pqr/pdb2pqr/
#  - python2 scons/scons.py install
#  - export PATH="/home/travis/pdb2pqr/:$PATH"
#  - #export PATH=/home/travis/build/samuelmurail/gromacs_py/gromacs_py:$PATH"
#  - ls ${TRAVIS_BUILD_DIR}
#
#branches:
#    only:
#      - master
#
#script:
#  - cd ${TRAVIS_BUILD_DIR}
#  - ./gromacs_py/test_gromacs_py.py
