language: python

python:
  - "3.6"

os:
  - linux

sudo: false

git:
  depth: false

#before_install: 
#  - python install 2.7 

install:
  - #git clone https://github.com/samuelmurail/gromacs_py.git
  - pwd
  - pip install -r requirements.txt
  - cd ..
  - git clone https://github.com/Electrostatics/apbs-pdb2pqr.git --branch master --depth=1
  - cd apbs-pdb2pqr/pdb2pqr/
  - python2 scons/scons.py install
  - export PATH="/home/travis/pdb2pqr/:$PATH"
  - #export PATH=/home/travis/build/samuelmurail/gromacs_py/gromacs_py:$PATH"
  - ls ${TRAVIS_BUILD_DIR}

branches:
    only:
      - master

script:
  - cd /home/travis/build/samuelmurail/gromacs_py/gromacs_py
  - ./test_gromacs_py.py