# Inspired by :
# https://github.com/astropy/ci-helpers/blob/master/.travis.yml
# And:
# https://github.com/Becksteinlab/GromacsWrapper/blob/master/.travis.yml

language: generic

os:
  - linux

git:
  depth: false

branches:
  only:
    - master

env:
  global:
    - GROMACS_VERSION=2019.1 
    - PYTHON_VERSION=3.6
    - CONDA_DEPENDENCIES="gromacs pandoc ipython"
    - CONDA_CHANNELS="conda-forge bioconda"

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.5
        - os: linux
          env: PYTHON_VERSION=3.7
        - os: osx
          env: GROMACS_VERSION=2018.5

install:
  # Install astropy to build python and gromacs with conda
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  # Install gromacs_py
  - pip install -r requirements_dev.txt
  # Install pdb2pqr
  # - cd ..
  # - git clone https://github.com/Electrostatics/apbs-pdb2pqr.git --branch master --depth=1
  # - cd apbs-pdb2pqr/pdb2pqr/
  # - python2 scons/scons.py install 
  # - export PATH="${HOME}/pdb2pqr/:$PATH"

script:
  - cd ${TRAVIS_BUILD_DIR}
  # Test gromacs_py
  # Need to add --ignore to avoid weird error, see: https://github.com/pytest-dev/pytest/issues/4782
  - pytest --ignore ci-helpers --cov-report=xml --cov=gromacs_py 
  # Build Doc:
  - cd docs
  - sphinx-build -b html . _build

after_success:
  # Launch pytest for codecov
  - cd ${TRAVIS_BUILD_DIR}
  - codecov